name: Release Nugets

on:
  workflow_dispatch:
    inputs:
      release_nugets:
        description: 'release to nuget.org'
        required: true
        type: boolean 

jobs:
  build:

    env:
      SOLUTION: 'Mapsui.sln'

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Prevent a shallow clone to allow git describe --tags

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    # .Net 7 update     
    - name: Setup .NET 7 SDK
      uses: actions/setup-dotnet@v3
      with:
         dotnet-version: |
           8.0.x
         include-prerelease: true
       
      # The version tag needs to be set before the release. If not if will fail on nuget publish.
    - name: Set VERSION_OF_RELEASE to last tag
      run: |
        echo ("VERSION_OF_RELEASE=" + $(git describe --tags --abbrev=0)) >> $env:GITHUB_ENV
        echo $VERSION_OF_RELEASE

    - name: install workloads
      run: Scripts/InstallDependencies.cmd

    - name: Test
      run: dotnet test ${{ env.SOLUTION }} --configuration Release --verbosity normal -p:Version=${{ env.VERSION_OF_RELEASE }}

    - name: Pack
      # The dlls and nupkgs will be built 'inputs.release_version' as version, overriding the version number in the Directory.Build.props.
      run: dotnet pack ${{ env.SOLUTION }} --configuration Release /p:Version=${{ env.VERSION_OF_RELEASE }} -o nugets

    - name: Upload nugets
      uses: actions/upload-artifact@v3
      with:
      # Upload the 'nugets' folder as artifact
        name: packages
        path: nugets/*.nupkg

    - name: Release NuGets
      if: ${{ inputs.release_nugets }} 
      run: nuget push "nugets\**\*.nupkg" -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_APIKEY}}
